django_app/tweets/tweet_search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.search, name='index'),
	url(r'results', views.results, name='results'),
	url(r'populate', views.populate, name='populate'),
	url(r'about', views.about, name='about'),
	url(r'checkup', views.checkup, name='checkup'),
	]

django_app/tweets/tweets/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls), 
    url(r'^', include('tweet_search.urls')), 
]

django_app/tweets/tweet_search/models.py
from django.db import models
import html.parser as htmlparser

class Hashtag(models.Model):
    name = models.CharField(max_length=140)

class TweetBucket(models.Model):
    timestamp = models.DateTimeField()
    count = models.IntegerField()
    hashtag = models.ForeignKey(Hashtag, on_delete=models.CASCADE)

    def formatted_timestamp(self):
        return self.timestamp.strftime("%Y-%m-%d")

    class Meta:
        ordering = ('timestamp',)

class Story(models.Model):
    timestamp = models.DateTimeField()
    url = models.URLField()
    headline = models.TextField()
    hashtag = models.ForeignKey(Hashtag, on_delete=models.CASCADE)

    def formatted_timestamp(self):
        return self.timestamp.strftime("%Y-%m-%d")

    def clean_headline(self):
        cleaned = self.headline.replace("'", "")
        cleaned = cleaned.replace("&", "and")
        cleaned = cleaned.replace('"', '')
        return cleaned

    class Meta:
        ordering = ('timestamp',)

django_app/tweets/tweet_search/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.middleware import csrf
import json
from django.core.exceptions import ObjectDoesNotExist
from tweet_search.models import Hashtag, TweetBucket, Story

def index(request):
	return render(request, 'tweet_search/index.html')

def results(request):
	'''
	Gets search term from user input, lowers it and removes # just in case!
	sends context to no_results if fails try, otherwise, send search term 
	and hashtag data from database into results page
	'''
	search_term = request.GET.get('search_term')

	search_term = search_term.lower()

	if search_term.startswith('#'):
		search_term = search_term[1:]

	simple_context = {
	'search_term': search_term,
	}

	hashtag_data = None
	try:
		hashtag_data = Hashtag.objects.get(name=search_term)
	except ObjectDoesNotExist:
		return render(request, 'tweet_search/no_results.html', simple_context)

	context = {
		'search_term': search_term,
		'hashtag_data': hashtag_data,
	}

	return render(request, 'tweet_search/results.html', context)

def search(request):
	return render(request, 'tweet_search/search.html')

def about(request):
	return render(request, 'tweet_search/about.html')

def populate(request):
	'''
	Populate the Postgres database with data passed
	'''
	# return the CSRF token
	if request.method == 'GET':
		csrf.get_token(request)
		return HttpResponse('ok')

	payload = json.loads(request.POST.get('payload'))

	# Delete any old data that exists at that hashtag
	hashtag_in_db = Hashtag.objects.filter(name=payload.get('hashtag'))
	hashtag_in_db.all().delete()

	# save hashtag data at Hashtag object
	hashtag = Hashtag(name=payload.get('hashtag'))
	hashtag.save()

	# save tweetbucket data at TweetBucket object
	for tweetbucket in payload.get('tweetbuckets'):
		timestamp = tweetbucket.get('datestring')
		count = tweetbucket.get('count')
		tb = TweetBucket(timestamp=timestamp, count=count, hashtag=hashtag)
		tb.save()

	# save story data at Story object
	for story in payload.get('stories'):
		timestamp = story.get('timestamp')
		url = story.get('url')
		headline = story.get('headline')
		s = Story(timestamp=timestamp, url=url, hashtag=hashtag, headline=headline)
		s.save()

	return HttpResponse('ok')

def checkup(request):
	'''
	print the number of hashtags and a list of hashtags in the postgres database
	'''
	context = {
		'hashtags': Hashtag.objects.all(),
	}

	return render(request, 'tweet_search/checkup.html', context)

django_app/tweets/tweet_search/templates/tweet_search/about.html
<head>
  <link rel="shortcut icon" href="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png" type="image/x-icon" />
  <title>VERY FUN TWEETS</title>
</head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>

<nav class="navbar navbar-default" style= "background-color:#82C5A7">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="./">
        <img alt="VTF" style="width:width:20px;height:20px;" src="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png">
      </a>
    </div>
      <p class="navbar-text">VFT</p>
    <p class="navbar-text navbar-right"><a href= "./about" class="navbar-link">ABOUT</a></p>
  </div>
</nav>

<style>
ul {
  margin-top: 10px;
  font-size: 16px;
}
</style>

<div class="container">
  <h1 class="text-center">About us!</h1>
</div

  <div class="row">
    <div class="col-md-4">
      <h3 class="text-center">the inside man</h3>
      <img src="https://drive.google.com/uc?export=view&id=15jwzaEc30VfVjQz_U1fgHF8NqefMP9Dy" alt="Chelsea" height="400" width="400"/>
      <ul>
        <li>Favorite Hashtag: #hatersgonnahate</li>
        <li>Favorite Emoji: 🙃</li>
        <li>Favorite Website: www.veryfuntweets.com</li>
      </ul>
    </div>
    <div class="col-md-4">
      <h3 class="text-center">the dreamer</h3>
      {% load static %}
      <img src="https://drive.google.com/uc?export=view&id=1FyDnfhfPqGnYKpqXG8BAghuAcf2Gv9SU" alt="Sush" height="400" width="400"/>
      <ul>
        <li>Favorite Hashtag: #til</li>
        <li>Favorite Emoji: 👻</li>
        <li>Favorite Website: www.veryfuntweets.com</li>
      </ul>
    </div>
    <div class="col-md-4">
      <h3 class="text-center">the money guy</h3>
      <img src="https://drive.google.com/uc?export=view&id=1mDreSGY5E5DHCiFb_GmIAMs0HgWOyk3q" alt="Haylee" height="400" width="400"/>
      <ul>
        <li>Favorite Hashtag: #LeslieKnope</li>
        <li>Favorite Emoji: 🤤</li>
        <li>Favorite Website: www.veryfuntweets.com</li>
      </ul>
    </div>
  </div>

django_app/tweets/tweet_search/templates/tweet_search/checkup.html
<!DOCTYPE html>

<head>
  <link rel="shortcut icon" href="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png" type="image/x-icon" />
  <title>VERY FUN TWEETS</title>
</head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>

<div style="margin-left: auto; margin-right:auto; width:700px;">


<h2># of Hashtags</h2>
  <h3>{{ hashtags.count }}</h3>

<h2>Hashtags</h2>
{% for hashtag in hashtags %}
  <p>{{ hashtag.name }}</p>
{% endfor %}

</div>

django_app/tweets/tweet_search/templates/tweet_search/index.html
<!DOCTYPE html>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>

<style>
.main{
	margin: auto;
}
</style>

<html>

<body>

<div style="margin-left: auto; margin-right:auto; width:700px;">

	<h1> VERY FUN TWEETS </h1>

	<h4> <a href="./tweet_search"> SEARCH </a> </h4>

</div>



 </body>
 </html>

django_app/tweets/tweet_search/templates/tweet_search/no_results.html
<head>
	<link rel="shortcut icon" href="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png" type="image/x-icon" />
	<title>VERY FUN TWEETS</title>
</head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>

<nav class="navbar navbar-default" style= "background-color:#82C5A7">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="./">
        <img alt="VTF" style="width:width:20px;height:20px;" src="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png">
      </a>
    </div>
      <p class="navbar-text">VFT</p>
    <p class="navbar-text navbar-right"><a href= "./about" class="navbar-link">ABOUT</a></p>
  </div>
</nav>



<div style="margin-left: auto; margin-right:auto; width:700px;">

	<h1> NO RESULTS FOUND </h1>

	  <h4>Sadly, #{{ search_term }} is not in our database...yet </h4>

		<IMG SRC="https://media3.giphy.com/media/l41lQpaXZo7GGWD0k/200.webp#1" width="400" height="250">

  <h4> <a href="./"> TRY ANOTHER SEARCH </a> </h4>
</div>

django_app/tweets/tweet_search/templates/tweet_search/results.html
<head>
  <link rel="shortcut icon" href="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png" type="image/x-icon" />
  <title>VERY FUN TWEETS</title>
</head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>

<nav class="navbar navbar-default" style= "background-color:#82C5A7">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="./">
        <img alt="VTF" style="width:width:20px;height:20px;" src="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png">
      </a>
    </div>
      <p class="navbar-text">VFT</p>
    <p class="navbar-text navbar-right"><a href= "./about" class="navbar-link">ABOUT</a></p>
  </div>
</nav>


  <div class="container">
    <h1 style = "margin-bottom: 50px">RESULTS #{{ search_term }}</h1>

    <div id="chart"></div>
    <div style="margin-left: auto; margin-right:auto; width:1000px;">
      <h6>*Results taken from random sample of 1% Twitter data </h6>
    </div>
  </div>


<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>

<script>

$(function () {
  var myChart = Highcharts.chart('chart', {
    chart: {
      type: 'spline'
    },
    title: {
      text: ''
    },
    legend: {
      enabled: false,
    },
    xAxis: {
      type: 'datetime',
      labels: {
        formatter: function() {
            return Highcharts.dateFormat('%d %b %Y', this.value)
        }
      },
    },
    plotOptions: {
    series: {
           marker: {
                enabled: true,
                symbol: 'circle',
                radius: 1,
                states: {
                    hover: {
                        enabled: true
                    }
                }
        },
      cursor: 'pointer',
        point: {
            events: {
                click: function() {
                  {% if this.option.label != "" %}
                    window.open(this.options.q)
                  {% endif %}
                }
              }
            }
        }
    },
    series: [{
      tooltip: {
        pointFormat: '<b>{point.label}</b><br/><b>count:  {point.y}</b><br/>'
      },
      data: [
        {% for tweet_bucket in hashtag_data.tweetbucket_set.all %}
        {% if tweet_bucket.formatted_timestamp != "2017-02-23" and tweet_bucket.formatted_timestamp != "2017-02-25" %}
        {
          x: Date.parse('{{ tweet_bucket.formatted_timestamp }}'),
          y: {{ tweet_bucket.count }},
          label: "",
          {% for story in hashtag_data.story_set.all%}
            {% if tweet_bucket.formatted_timestamp == story.formatted_timestamp %}
              q: '{{ story.url }}',
              label: '{{ story.clean_headline }}',
              marker: {symbol: 'url(http://emojipedia-us.s3.amazonaws.com/cache/29/1e/291e8fa842dc88d96a03fc553bfc4000.png)',
              width: 40,
              height: 40,
            }
            {% endif %}
          {% endfor %}
        },
        {% endif %}
        {% endfor %}
      ]
    }]
  });
});

</script>


<div class="container">
  <h3> <a href="./"> TRY ANOTHER SEARCH </a> </h3>
</div>

django_app/tweets/tweet_search/templates/tweet_search/search.html
<!DOCTYPE html>

<head>
  <link rel="shortcut icon" href="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png" type="image/x-icon" />
  <title>VERY FUN TWEETS</title>
</head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"/>

<html>

<body>

<nav class="navbar navbar-default" style= "background-color:#82C5A7">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="./">
        <img alt="VTF" style="width:width:20px;height:20px;" src="https://emojipedia-us.s3.amazonaws.com/thumbs/320/mozilla/36/rocket_1f680.png">
      </a>
    </div>
      <p class="navbar-text">VFT</p>
    <p class="navbar-text navbar-right"><a href= "./about" class="navbar-link">ABOUT</a></p>
  </div>
</nav>

<div style="margin-left: auto; margin-right:auto; width:700px;">

	<h1> VERY FUN TWEETS </h1>

	<form action="/results">
	  Enter a hashtag to find out why it spiked!<br>
	  <button style="float:right;"> <i class="glyphicon glyphicon-search"></i></button>
	  <div style="overflow:hidden; padding-right: .5em;">
	  	<input type="text" style="width:100%;" id="search_term" name="search_term"><br>
	  </div>
	 </form>

</div>

<script>
(function () {
  var EMOJI = [
		'🐙', '🐝', '🌴', '🌵', '🍊', '🍉', '🌮', '🍟', '🍦', '🏈', '🇮🇳', '🇺🇸', '🇨🇦',
		'💖', '🎈', '👩‍🔬', '⚽️', '🍔', '👩‍🚀', '🍕', '🍍', '🥑', '🐳', '🦄', '👰', '👻', '🐶',
		'🐷', '🐳', '🐚', '🔥', '🤢', '🍳', '🍿', '💰', '💾', '💝', '🤤', '🌈'
  ];

  function makeFloatingEmoji() {
    // Create the element
    var element = document.createElement('div');
    element.classList.add('floating-emoji');
    // Add an emoji
    element.innerHTML = EMOJI[Math.floor(Math.random()*EMOJI.length)];;
    // Make it fall for a randomish amount of time
    var randomDuration = randomNumberBetween(7500, 10000);
    element.style.animationDuration = randomDuration + 'ms';
    // Random left value
    var randomLeft = randomNumberBetween(1, 99);
    element.style.left = randomLeft + '%';
		element.style.position = 'fixed';
		element.style.top = 0;
		element.style.opacity = 1;
		element.style.animation = 'fall-from-top 4000ms linear both';
    // Append to body
    document.body.appendChild(element);
    // Fade out and remove the element
    window.setTimeout(function () {document.body.removeChild(element)}, randomDuration);
  }
  function randomNumberBetween(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }
  var currentKeyframes = null;
  function createKeyframes() {
    var keyframe = document.createElement('style');
    keyframe.innerHTML = "@keyframes fall-from-top { \n\
      0% { transform: translateY(-30px); } \n\
      100% { transform: translateY(" + (window.innerHeight + 10) + "px); } \n\
    }";
    if (currentKeyframes !== null) { document.head.removeChild(currentKeyframes) }
    document.head.appendChild(keyframe);
  }
  document.addEventListener("DOMContentLoaded", function(event) {
    createKeyframes();
    window.addEventListener('resize', createKeyframes);
    for (var i = 0; i < 3; i++) { makeFloatingEmoji() }
    window.setInterval(makeFloatingEmoji, 200);
  });
})()
</script>


 </body>
 </html>